services:
  server:
    build: .
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 7080:2000

    env_file: ".env.prod"
    environment:
      - DATABASE_URI=postgresql+psycopg2://postgres:postgres@db:5432/DB
      - REDIS_HOST=redis


  db:
    image: postgres
    volumes:
      - ./pg_data/data:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=DB

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  dnet:
    external: true
