"""essage=add limits

Revision ID: f07133d20479
Revises: 4a5f9237aab0
Create Date: 2025-04-07 15:13:17.673598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07133d20479'
down_revision: Union[str, None] = '4a5f9237aab0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('limit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('category', 'created_at')
    op.drop_column('payment', 'money_come_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('money_come_type', sa.VARCHAR(length=7), nullable=False))
    op.add_column('category', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.drop_table('limit')
    # ### end Alembic commands ###
